name: StyLua

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  luacheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Check format
        uses: JohnnyMorganz/stylua-action@b6661824b86c9c33121bed87a778b660ba90cf77 # v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          args: --check .
